apiVersion: v1
kind: Service
metadata:
  name: crud-api-service
spec:
  type: NodePort
  selector:
    app: crud-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30008 # Exposes it on a fixed Minikube port